### ISSUE TITLE
Config file error when starting Butler

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#1183]
Creating a separate issue for this, in order not to cause confusion in the original issue #1141.
Let's use this new issue for discussions going forward regarding your config file issue, @PavelKassitchev .

Hi, newRelic lines are commented as in the samples above but I do get the same error
![butler](https://github.com/ptarmiganlabs/butler/assets/37771913/b5377a29-6128-4d38-b5ed-0224f14ea11a)
Butler version 12.4.0

_Originally posted by @PavelKassitchev in https://github.com/ptarmiganlabs/butler/discussions/1141#discussioncomment-9871741_

**Comment by mountaindude** [comment]
@PavelKassitchev, what computer and OS and OS version are you running Butler on?

**Comment by PavelKassitchev** [comment]
FUJITSU PRIMERGY RX2530 M2,
Microsoft Windows Server 2012 R2 Standard

**Comment by mountaindude** [comment]
@PavelKassitchev, 

I have looked into this now and your config file works just fine here. 
Have tested it with Butler 12.4.0 (same that you used) on both WinSrv 2016, Ubuntu and macOS.

So... there is something that makes your Butler server special, causing the code that gets information about the server to fail (the error occurs in the "Getting host info..." section).
I will keep investigating here, but if you can share the details of your server that would be useful.

Is it a virtual machine? Which Hypervisor if so (VMWare, HyperV, ...)?
Which operation system and version?
How much memory?

**Comment by PavelKassitchev** [comment]
Thank you! :)
I am not there right now so I will reply in a day or so

**Comment by mountaindude** [comment]
@PavelKassitchev 

There is a new Butler version, 12.4.1, available on the [Releases page](https://github.com/ptarmiganlabs/butler/releases). 
Direct download link [here](https://github.com/ptarmiganlabs/butler/releases/download/butler-v12.4.1/butler-12.4.1-win.zip).

It adds a bit more logging to the part of Butler that is causing you troubles. 
If you use this new version instead it will give more information about exactly what part of Butler is not working as intended.

Please give it a try if you have a few minutes to spare, then report back the error message here.

Slightly more technical explanation of what's going on:

- Butler uses a package called [SystemInformation](https://github.com/sebhildebrandt/systeminformation) to get info about the server on which it is running.
- That package is great and works without issues in vast majority of cases, but it seems it is in some cases not able to correctly determine how much memory is present in the computer where it is running.
- This is what's happening in your case: SystemInformation reports an error and doesn't return the data Butler needs.
- Butler is used in lots of Qlik Sense environments out there, so far I've only seen this issue 2-3 times. And I have never been able to replicate it, which is frustrating.
- I have reported the issue to the maintainers of SystemInformation. I am also working with them trying to understand what's going on.

**Comment by mountaindude** [comment]
@PavelKassitchev 

Update: 🎉

There indeed was a nasty little bug in Butler. 
It shows itself when the server where Butler is running has a non-standard setup for network interfaces (or no network interfaces enabled at all).

Anyways, version 12.4.2 is being built right now and will address this bug.
Will be available from the [Releases page](https://github.com/ptarmiganlabs/butler/releases), as usual.

**Comment by mountaindude** [comment]
...and a final comment.

Your config file is set up so that it will start Butler, but the Butler will then exit.
There simply isn't anything enabled in the config file..

I guess you started looking into using Butler for some reason - maybe getting nice alert emails when Qlik Sense reload tasks fail? 

The [setup section](https://butler.ptarmiganlabs.com/docs/getting-started/setup/) of the [Butler documentation site](https://butler.ptarmiganlabs.com) has plenty of information to help you along the way.

**Comment by PavelKassitchev** [comment]
Thank you very much! Release 12.4.2 has worked!! :)
Yes, sure, my next step will be setting up necessary functions in the config files

**Comment by mountaindude** [comment]
> Thank you very much! Release 12.4.2 has worked!! :) Yes, sure, my next step will be setting up necessary functions in the config files

Awesome - happy to hear that!
