### ISSUE TITLE
Unhandled exception when getting QSEoW app script log

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#1274]
### What version of Butler are you using?

13.0.0

### What command did you use to start Butler?

-

### What operating system are you using?

Windows Server 2019

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

2024-May IR

### Describe the Bug

Possible regression, this worked reliably in pre 13.0 versions.

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/ce0e5726-b890-4e58-9669-46e11d7d6d5b">

**Comment by mountaindude** [comment]
Indeed, looks like a regression bug that was introduced in 13.0.
The bug has been fixed and will be included in next release, due out in a day or two.

**Comment by mountaindude** [comment]
@Chase-Stevison 
This issue was fixed in v 13.1 which was release just now.

https://github.com/ptarmiganlabs/butler/releases/tag/butler-v13.1.0

**Comment by Chase-Stevison** [comment]
Thanks @mountaindude!
