### ISSUE TITLE
Extra closing table tag in handlebar configs

### ISSUE THREAD

**Issue by Chase-Stevison** [ptarmiganlabs/butler#1292]
### What version of Butler are you using?

13.1.0

### What command did you use to start Butler?

.\butler.exe -c .\config\production.yaml

### What operating system are you using?

Windows Server 2019

### What CPU architecture are you using?

Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz

### What Qlik Sense versions are you using?

Feb 2023 Patch 3

### Describe the Bug

The following handlebars configs have an extra closing table tag which causes the emails to not have properly formatted tables:

https://github.com/ptarmiganlabs/butler/blob/4123b576a08b19947e3a3e54b4995374972a95a9/src/config/email_templates/aborted-reload-qseow.handlebars#L5

https://github.com/ptarmiganlabs/butler/blob/4123b576a08b19947e3a3e54b4995374972a95a9/src/config/email_templates/success-reload-qseow.handlebars#L5

Example:
![image](https://github.com/user-attachments/assets/fc6f58b6-d242-4763-a7de-f71f8c311f08)

I simply removed the </table> tags from line 5 of those files in my environment, but I figured I'd mention it improve the out of the box experience. As always, thanks for the continued improvements to your suite of Qlik tools!

### Expected Behavior

Properly formatted tables in the alert emails for aborted and successful reloads. The output should be similar to:
![image](https://github.com/user-attachments/assets/8fbf10b9-12f7-4677-bc1d-312c6efe6b32)

### To Reproduce

Simply use the handlebar configs included in the current release.

**Comment by mountaindude** [comment]
Nice catch.
Fixed in next version of Butler.
