### ISSUE TITLE
Sample QVF

### ISSUE THREAD

**Issue by JochemZ** [ptarmiganlabs/butler#364]
i can't open the sample qvf's for Butler??
Error: data is corrupt (Desktop and Server).

Hope you can help me

**Comment by mountaindude** [comment]
Indeed, those QVFs seem quite broken. Strange. 
Will have to look into that of course.

Meanwhile, attached is the 7.0 demo app. See if this works..

If you plan to use Butler's REST API (which is what the demo app is really about - showing how those APIs can be used) you must also (probably, depends on what Butler APIs you plan to use) create the associated data connections.
More info [here](https://butler.ptarmiganlabs.com/docs/getting-started/setup/data-connections/).

**Comment by JochemZ** [comment]
Thnx!!

I installed Butler on my laptop, and got it all working now.
Needed the FileMove functionality, and this is working fine, only problem now is the speed (139 small files in 6 minutes?)

**Comment by mountaindude** [comment]
True. And the execution of the Qlik script itself is also something to take
into account. If that script runs slowly it will impact the total time you
measure.
