### ISSUE TITLE
Absent standalone binaries for Linux

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/butler#540]
### What version of Butler are you using?

7.2.2

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler.

v14.18.0

### What command did you use to start Butler?

./opt/butler/butler.js

### What operating system are you using?

Debian 11

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2022-February

### Describe the Bug

In 7.2.2 anonced:
Create standalone binaries for Win, macOS, Linux ([6ae4e43](https://github.com/ptarmiganlabs/butler/commit/6ae4e438003328aa398e384ecd943d585f9c5c00))
But in none of the versions, starting from 7.2.2, there are no Linux binaries.

**Comment by mountaindude** [comment]
Ahh... ehhh... hrmmmf...
You know, you're absolutely right. 
I was looking into options for signing Linux binaries way back then, got side-tracked working on something else and totally forgot about those Linux binaries.... 

Sorry about that.
Will enable those builds in the build pipeline again.

**Comment by mountaindude** [comment]
@chevcheli0s 

Version 8.4.2 was just released, including a Linux binary.
It's built and tested on Ubuntu 20.04, will hopefully work on other distributions too.

https://github.com/ptarmiganlabs/butler/releases
