### ISSUE TITLE
reloadTaskAborted and reloadTaskAborted recipients empty lists

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/butler#640]
### What version of Butler are you using?

8.6.2

### What command did you use to start Butler?

/opt/butler-v8.6.2/butler --configfile ./config/production.yaml

### What operating system are you using?

Debian 11

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2022-November sp13

### Describe the Bug

When in config sections I use empty recipients lists
```
reloadTaskAborted:
...
  recipients:

...

reloadTaskAborted:
...
  recipients:

```
I receive error
```
butler[587982]: /snapshot/butler/src/lib/smtp.js:578
butler[587982]:         if (globalSendList.length > 0) {
butler[587982]:                            ^
butler[587982]: TypeError: Cannot read properties of null (reading 'length')
butler[587982]:     at Object.sendReloadTaskAbortedNotificationEmail (/snapshot/butler/src/lib/smtp.js:578:28)
systemd[1]: butler-prod.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: butler-prod.service: Failed with result 'exit-code'.
```

**Comment by chevcheli0s** [comment]
Same with empty excludeOwner
```
excludeOwner:
  user:

```
```
butler[603084]: /snapshot/butler/src/lib/smtp.js:416
butler[603084]:             const matchExcludedUsers = excludeUsers.filter(
butler[603084]:                                                     ^
butler[603084]: TypeError: Cannot read properties of null (reading 'filter')
butler[603084]:     at Object.sendReloadTaskFailureNotificationEmail (/snapshot/butler/src/lib/smtp.js:416:53)
```

**Comment by mountaindude** [comment]
Long overdue, a fix for this is coming in next version of Butler.
Thx for reporting the issue btw!

The workaround would be to disable (in the YAML config file) the features causing problems, but it's of course better that Butler itself is resilient and deals with empty recipient lists in a good way.
