### ISSUE TITLE
Teams Service Notifications not sending despite being enabled.

### ISSUE THREAD

**Issue by Chase-Stevison** [ptarmiganlabs/butler#758]
### What version of Butler are you using?

9.1.1

### What command did you use to start Butler?

.\butler.exe -c .\config\production.yaml

### What operating system are you using?

Windows Server 2019

### What CPU architecture are you using?

Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz

### What Qlik Sense versions are you using?

Feb 2023 Patch 3

### Describe the Bug

Service monitor notifications are unable to send via teams despite being enabled.  It looks like the wrong config value is read when checking if the teams notification is enabled for the service monitor.

Line 212 in src/lib/msteams_notification.js references the configuration value for Slack rather than MS Teams.

if (!globals.config.get('Butler.serviceMonitor.alertDestination.slack.enable')) {
should be
if (!globals.config.get('Butler.serviceMonitor.alertDestination.teams.enable')) {

### Expected Behavior

Teams notifications sent when service monitor event detected.

### To Reproduce

Start or Stop a monitored Service while Teams notifications are enabled, but Slack notifications are disabled.

**Comment by mountaindude** [comment]
Ouch, a classic copy-paste-error. 
The Slack integration was probably done first, that code was then copied to the Teams integration. 

Will see to this bug in a day or two, together with some other improvements.

Thanks for reporting it!
