### ISSUE TITLE
Custom services monitoring

### ISSUE THREAD

**Issue by bintocher** [ptarmiganlabs/butler#850]
### What version of Butler SOS are you using?

9.6.1

### What command did you use to start Butler SOS?

docke-compose

### What operating system are you using?

ubuntu 20

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2023 August SR3

### Describe the Bug

it is necessary to specify services for monitoring for each server

i have a 5-nodes qlik sense cluster,
![image](https://github.com/ptarmiganlabs/butler-sos/assets/8188055/19c4f6ae-5b22-4fce-9d6f-9de1431166ae)

1 node - for etl (central node, repository, scheduler, printing, proxy, engine)
![image](https://github.com/ptarmiganlabs/butler-sos/assets/8188055/8c1b9344-7b31-428e-8a40-3dcc21eef155)

1 node - for dev (repository, scheduler, printing, engine)
![image](https://github.com/ptarmiganlabs/butler-sos/assets/8188055/6a36d3c0-fb3c-4a04-9bf3-a9f330dd0eb4)

2 nodes - for prod (repository, engine, printing)
![image](https://github.com/ptarmiganlabs/butler-sos/assets/8188055/00abbf92-19c9-43b8-998e-15bbd4529111)

1 node - for proxy (repository, proxy)
![image](https://github.com/ptarmiganlabs/butler-sos/assets/8188055/1ac4a27f-4ae2-46ee-8bc8-91e447e7351f)

in grafana i get error every minute from proxy-node:

{"source":"qseow-repository",
"log_row":"1196",
"ts_iso":"20231023T093326.789+0300",
"ts_local":"2023-10-23 09:33:26,
789",
"level":"ERROR",
"host":"proxy-qs.domain.com",
"subsystem":"System.Repository.Repository.Communication.Clients.EngineClient",
"windows_user":"domain\\user_srv",
"message":"API call to Engine service was not successful: Failed to get app 'StaticByteSize'.",
"exception_message":"System.ArgumentNullException: Value cannot be null.↵↓Parameter name: stream↵↓   at System.IO.StreamReader..ctor(Stream stream,
 Encoding encoding,
 Boolean detectEncodingFromByteOrderMarks,
 Int32 bufferSize,
 Boolean leaveOpen)↵↓   at System.IO.StreamReader..ctor(Stream stream)↵↓   at Repository.Communication.Clients.EngineClient.GetAppStaticByteSize(App app)",
"user_directory":"",
"user_id":"",
"command":"",
"result_code":"",
"origin":"",
"context":"System.ArgumentNullException: Value cannot be null.\r\nParameter name: stream\r\n   at System.IO.StreamReader..ctor(Stream stream,
 Encoding encoding,
 Boolean detectEncodingFromByteOrderMarks,
 Int32 bufferSize,
 Boolean leaveOpen)\r\n   at System.IO.StreamReader..ctor(Stream stream)\r\n   at Repository.Communication.Clients.EngineClient.GetAppStaticByteSize(App app)\r\n",
"user_full":""}

**Comment by mountaindude** [comment]
Latest version, [9.3.1](https://github.com/ptarmiganlabs/butler/releases/tag/v9.3.1), adds better support for Windows services.
Among other things there is now better logging when failing to connect to remote Windows servers where services should be monitored.
